export const SELECT_COUNTRY = 'SELECT_COUNTRY';

// Covid types
export const FETCH_COVID_REQUEST = 'FETCH_COVID_REQUEST';
export const FETCH_COVID_SUCCESS = 'FETCH_COVID_SUCCESS';
export const FETCH_COVID_FAIL = 'FETCH_COVID_FAIL';

// Global Covid types
export const FETCH_GLOBALS_REQUEST = 'FETCH_GLOBALS_REQUEST';
export const FETCH_GLOBALS_SUCCESS = 'FETCH_GLOBALS_SUCCESS';
export const FETCH_GLOBALS_FAIL = 'FETCH_GLOBALS_FAIL';

// News Covid types
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';
